name: cmc-tenent
region: nyc
# DigitalOcean App Platform spec generated for multi-service deployment.
# Fill in the TODO_* placeholders with your real values before deploying.

services:
  - name: api
    source_dir: apps/api
    dockerfile_path: Dockerfile
    http_port: 8080
    instance_size_slug: basic-xxs
    instance_count: 1
    envs:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        value: ${DATABASE_JDBC_URL:-jdbc:postgresql://db-host:5432/clinic_multi_tenant}
        scope: RUN_AND_BUILD_TIME
      - key: SPRING_DATASOURCE_USERNAME
        value: ${DATABASE_USER:-clinic}
        scope: RUN_AND_BUILD_TIME
      - key: SPRING_DATASOURCE_PASSWORD
        value: ${DATABASE_PASSWORD:-change-me}
        scope: RUN_AND_BUILD_TIME
      - key: PUBLIC_APP_ORIGIN
        value: https://your-web-domain
      - key: ADMIN_APP_ORIGIN
        value: https://your-admin-domain
      - key: SAAS_ADMIN_APP_ORIGIN
        value: https://your-saas-admin-domain
      - key: SENDGRID_API_KEY
        value: TODO_SENDGRID_API_KEY
        type: SECRET
      - key: EMAIL_FROM
        value: info@cliniqax.com
      - key: EMAIL_FROM_NAME
        value: Cliniqax
      - key: EMAIL_ENABLED
        value: "true"
      - key: PAYPAL_CLIENT_ID
        value: TODO_PAYPAL_CLIENT_ID
        type: SECRET
      - key: PAYPAL_CLIENT_SECRET
        value: TODO_PAYPAL_CLIENT_SECRET
        type: SECRET
      - key: PAYPAL_WEBHOOK_ID
        value: TODO_PAYPAL_WEBHOOK_ID
        type: SECRET
      - key: PAYPAL_ENVIRONMENT
        value: sandbox
      - key: PAYPAL_BASE_URL
        value: https://api-m.sandbox.paypal.com
      - key: PAYPAL_ENCRYPTION_KEY
        value: TODO_PAYPAL_ENCRYPTION_KEY_32B
        type: SECRET
      - key: APP_BASE_URL
        value: https://your-web-domain
      - key: GOOGLE_CLIENT_ID
        value: TODO_GOOGLE_CLIENT_ID
        type: SECRET
      - key: GOOGLE_CLIENT_SECRET
        value: TODO_GOOGLE_CLIENT_SECRET
        type: SECRET
      - key: GOOGLE_REDIRECT_URI
        value: https://your-web-domain/auth/google/callback
      - key: CLOUDFLARE_ACCOUNT_ID
        value: TODO_CLOUDFLARE_ACCOUNT_ID
        type: SECRET
      - key: CLOUDFLARE_API_TOKEN
        value: TODO_CLOUDFLARE_API_TOKEN
        type: SECRET
      - key: CLOUDFLARE_BASE_URL
        value: https://api.cloudflare.com/client/v4
      - key: CLOUDFLARE_DELIVERY_URL
        value: ""
      - key: CLOUDFLARE_IMAGES_MOCK_MODE
        value: "true"

  - name: web
    source_dir: apps/web-next
    dockerfile_path: Dockerfile
    http_port: 3001
    instance_size_slug: basic-xxs
    instance_count: 1
    envs:
      - key: NEXT_PUBLIC_API_URL
        value: https://your-api-domain/public
      - key: NEXT_SERVER_API_URL
        value: https://your-api-domain/public
      - key: NEXT_SERVER_API_BASE_URL
        value: https://your-api-domain
      - key: DATABASE_URL
        value: ${DATABASE_URL:-postgresql://user:password@db-host:5432/clinic_multi_tenant}
        scope: RUN_AND_BUILD_TIME

  - name: admin
    source_dir: apps/admin-nuxt
    dockerfile_path: Dockerfile
    http_port: 3000
    instance_size_slug: basic-xxs
    instance_count: 1
    envs:
      - key: NUXT_PUBLIC_API_BASE
        value: https://your-api-domain/admin
      - key: NUXT_PRIVATE_API_BASE
        value: https://your-api-domain/admin
      - key: NODE_ENV
        value: production

  - name: saas-admin
    source_dir: apps/saas-admin-nuxt
    dockerfile_path: Dockerfile
    http_port: 3002
    instance_size_slug: basic-xxs
    instance_count: 1
    envs:
      - key: NUXT_PUBLIC_API_BASE
        value: https://your-api-domain
      - key: NUXT_PUBLIC_SAAS_API_BASE
        value: https://your-api-domain/saas
      - key: NUXT_PUBLIC_APP_NAME
        value: SAAS Manager Panel
      - key: NUXT_PUBLIC_APP_URL
        value: https://your-saas-admin-domain
      - key: NUXT_PUBLIC_ENABLE_ANALYTICS
        value: "true"
      - key: NUXT_PUBLIC_ENABLE_AUDIT_LOGS
        value: "true"
      - key: NODE_ENV
        value: production

  - name: saas-landing
    source_dir: apps/saas-landing
    dockerfile_path: Dockerfile
    http_port: 3003
    instance_size_slug: basic-xxs
    instance_count: 1
    envs:
      - key: NEXT_PUBLIC_API_BASE_URL
        value: https://your-api-domain
      - key: NEXT_PUBLIC_APP_URL
        value: https://your-landing-domain
      - key: NEXT_PUBLIC_PAYPAL_CLIENT_ID
        value: TODO_PAYPAL_CLIENT_ID
        type: SECRET
      - key: NEXT_PUBLIC_HERO_VIDEO_URL
        value: https://www.youtube.com/embed/T8lXiW5x8_s?autoplay=1&mute=1&loop=1
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3003"

routes:
  - path: /
    service: web
  - path: /admin(/.*)?
    service: admin
    preserve_path_prefix: true
  - path: /saas-admin(/.*)?
    service: saas-admin
    preserve_path_prefix: true
  - path: /landing(/.*)?
    service: saas-landing
    preserve_path_prefix: true
