CREATE TABLE tags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   tenant_id BIGINT NOT NULL,
   name VARCHAR(50) NOT NULL,
   color VARCHAR(20),
   created_by BIGINT,
   created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   updated_at TIMESTAMP WITHOUT TIME ZONE,
   deleted_at TIMESTAMP WITHOUT TIME ZONE,
   CONSTRAINT pk_tags PRIMARY KEY (id)
);

CREATE TABLE patient_tags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   patient_id BIGINT NOT NULL,
   tag_id BIGINT NOT NULL,
   created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   CONSTRAINT pk_patient_tags PRIMARY KEY (id)
);

ALTER TABLE tags ADD CONSTRAINT fk_tags_on_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id);

ALTER TABLE patient_tags ADD CONSTRAINT fk_patient_tags_on_patient FOREIGN KEY (patient_id) REFERENCES patients (id);

ALTER TABLE patient_tags ADD CONSTRAINT fk_patient_tags_on_tag FOREIGN KEY (tag_id) REFERENCES tags (id);

CREATE UNIQUE INDEX idx_tags_tenant_name ON tags (tenant_id, lower(name)) WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX idx_patient_tags_patient_tag ON patient_tags (patient_id, tag_id);

CREATE INDEX idx_patient_tags_tag_id ON patient_tags (tag_id);
